export const CERTIFICATION_ID = 'aws-saa-c03'

export interface ConceptDefinition {
  slug: string
  name: string
  description: string
  domainSlug: string
  topicSlug: string
  difficulty: number // 0-1
  keyFacts: string[]
  examTips: string[]
  awsServices: string[]
  confusedWith: string[]
}

export interface TopicDefinition {
  slug: string
  name: string
  domainSlug: string
}

export interface DomainDefinition {
  slug: string
  name: string
  examWeightPercent: number
  color: string
  description: string
}

export const DOMAINS: DomainDefinition[] = [
  {
    slug: 'resilient-architecture',
    name: 'Arquitectura Resiliente',
    examWeightPercent: 30,
    color: '#6366f1',
    description: 'Diseñar soluciones multi-tier resilientes, tolerantes a fallos y recuperación ante desastres',
  },
  {
    slug: 'performant-architecture',
    name: 'Arquitectura de Alto Rendimiento',
    examWeightPercent: 28,
    color: '#10b981',
    description: 'Seleccionar soluciones de almacenamiento, computación, red y DB de alto rendimiento',
  },
  {
    slug: 'secure-architecture',
    name: 'Arquitectura Segura',
    examWeightPercent: 24,
    color: '#f59e0b',
    description: 'Diseñar acceso seguro, workloads seguros y protección de datos',
  },
  {
    slug: 'cost-optimized-architecture',
    name: 'Arquitectura Optimizada en Costos',
    examWeightPercent: 18,
    color: '#ef4444',
    description: 'Identificar soluciones de almacenamiento, computación y servicios optimizados en costos',
  },
]

export const TOPICS: TopicDefinition[] = [
  // Resilient
  { slug: 'ec2-compute', name: 'EC2 & Compute', domainSlug: 'resilient-architecture' },
  { slug: 'storage-resilience', name: 'Almacenamiento Resiliente', domainSlug: 'resilient-architecture' },
  { slug: 'database-resilience', name: 'Bases de Datos Resilientes', domainSlug: 'resilient-architecture' },
  { slug: 'networking-connectivity', name: 'Redes y Conectividad', domainSlug: 'resilient-architecture' },
  // Performant
  { slug: 'content-delivery', name: 'Entrega de Contenido', domainSlug: 'performant-architecture' },
  { slug: 'messaging-integration', name: 'Mensajería e Integración', domainSlug: 'performant-architecture' },
  { slug: 'containers-serverless', name: 'Contenedores y Serverless', domainSlug: 'performant-architecture' },
  { slug: 'performance-database', name: 'BD de Alto Rendimiento', domainSlug: 'performant-architecture' },
  // Secure
  { slug: 'iam-identity', name: 'IAM e Identidad', domainSlug: 'secure-architecture' },
  { slug: 'data-protection', name: 'Protección de Datos', domainSlug: 'secure-architecture' },
  { slug: 'network-security', name: 'Seguridad de Red', domainSlug: 'secure-architecture' },
  // Cost Optimized
  { slug: 'cost-compute', name: 'Cómputo Optimizado', domainSlug: 'cost-optimized-architecture' },
  { slug: 'cost-storage', name: 'Almacenamiento Optimizado', domainSlug: 'cost-optimized-architecture' },
  { slug: 'cost-governance', name: 'Gobierno de Costos', domainSlug: 'cost-optimized-architecture' },
]

export const CONCEPTS: ConceptDefinition[] = [
  // ---- EC2 ----
  {
    slug: 'ec2-instance-types',
    name: 'Tipos de Instancias EC2',
    description: 'Familias de instancias EC2 y cuándo usar cada una (General Purpose, Compute Optimized, Memory Optimized, Storage Optimized, Accelerated Computing)',
    domainSlug: 'resilient-architecture',
    topicSlug: 'ec2-compute',
    difficulty: 0.4,
    keyFacts: [
      'T family: burstable, baseline CPU + burst credits — ideal para workloads esporádicos',
      'M family (General Purpose): balance CPU/memoria — webservers, app servers',
      'C family (Compute Optimized): alta relación CPU/memoria — HPC, batch, ML inference',
      'R/X/Z family (Memory Optimized): grandes in-memory databases, SAP HANA',
      'I/D family (Storage Optimized): NVMe local SSD, alto IOPS — bases de datos NoSQL',
      'P/G/Inf family (Accelerated): GPUs para ML training, video encoding',
    ],
    examTips: [
      'Si dice "intermittent workloads" → T family con unlimited credits OFF',
      'Si dice "lowest latency" con local storage → Instance store, no EBS',
      'HPC siempre → C family + placement group cluster',
    ],
    awsServices: ['EC2', 'Auto Scaling'],
    confusedWith: ['ec2-pricing-models'],
  },
  {
    slug: 'ec2-pricing-models',
    name: 'Modelos de Precios EC2',
    description: 'On-Demand, Reserved (Standard/Convertible), Spot, Dedicated Hosts y Savings Plans',
    domainSlug: 'cost-optimized-architecture',
    topicSlug: 'cost-compute',
    difficulty: 0.5,
    keyFacts: [
      'On-Demand: pago por hora/segundo, sin compromiso — baseline',
      'Reserved Standard 1y/3y: hasta 72% descuento, AZ específica o Region',
      'Reserved Convertible: hasta 54% descuento, puede cambiar familia/OS',
      'Spot: hasta 90% descuento, puede ser interrumpido con 2min de aviso',
      'Dedicated Host: servidor físico dedicado — licensing BYOL (Oracle, Windows)',
      'Savings Plans: compromiso de $/hora por 1-3 años, más flexible que Reserved',
    ],
    examTips: [
      'Spot → workloads tolerantes a fallos, batch, análisis de datos, CI/CD',
      'Dedicated Host → compliance, licensing socket/core (Oracle DB)',
      'Savings Plans > Reserved Convertible en flexibilidad',
    ],
    awsServices: ['EC2', 'Savings Plans', 'Cost Explorer'],
    confusedWith: ['ec2-instance-types'],
  },
  {
    slug: 'ec2-auto-scaling',
    name: 'Auto Scaling Groups (ASG)',
    description: 'Escalado automático de instancias EC2 basado en políticas, schedules y métricas',
    domainSlug: 'resilient-architecture',
    topicSlug: 'ec2-compute',
    difficulty: 0.5,
    keyFacts: [
      'Launch Template reemplaza a Launch Configuration (más features)',
      'Scaling policies: Target Tracking (más simple), Step Scaling, Simple Scaling',
      'Target Tracking con CPU 50% → el más recomendado en el examen',
      'Cooldown period: evita double-scaling (default 300s)',
      'Health checks: EC2 (default) o ELB — ELB es más completo',
      'Lifecycle hooks: pausar instancias en launch/terminate para custom logic',
    ],
    examTips: [
      'Para "scale out fast" → Step Scaling o Target Tracking con alarmas agresivas',
      '"Replace unhealthy instances" → siempre ASG con ELB health checks',
      'Predictive Scaling usa ML — para workloads con patrones regulares',
    ],
    awsServices: ['EC2 Auto Scaling', 'ELB', 'CloudWatch'],
    confusedWith: ['elb-types'],
  },
  {
    slug: 'ec2-placement-groups',
    name: 'Placement Groups EC2',
    description: 'Cluster, Spread y Partition — estrategias de ubicación física para EC2',
    domainSlug: 'performant-architecture',
    topicSlug: 'ec2-compute',
    difficulty: 0.6,
    keyFacts: [
      'Cluster: mismo rack/AZ — ultra-low latency, 10Gbps+ network — SOLO UNA AZ',
      'Spread: instancias en racks distintos — max 7 por AZ — alta disponibilidad crítica',
      'Partition: grupos de instancias en particiones aisladas — Hadoop, Kafka, Cassandra',
      'Cluster tiene ALTO riesgo de AZ failure, Spread es para resiliencia máxima',
    ],
    examTips: [
      'HPC + MPI + "lowest latency" → Cluster placement group',
      '"Cannot tolerate correlated hardware failure" → Spread',
      '"Distributed big data with rack awareness" → Partition',
    ],
    awsServices: ['EC2'],
    confusedWith: ['ec2-auto-scaling'],
  },
  // ---- S3 ----
  {
    slug: 's3-storage-classes',
    name: 'Clases de Almacenamiento S3',
    description: 'Standard, IA, One Zone-IA, Glacier, Deep Archive y sus trade-offs de costo/disponibilidad',
    domainSlug: 'cost-optimized-architecture',
    topicSlug: 'cost-storage',
    difficulty: 0.5,
    keyFacts: [
      'Standard: 99.99% availability, 3+ AZ, acceso instantáneo — datos frecuentes',
      'Standard-IA: 99.9% availability, 3 AZ, retrieval fee — datos infrequentes (>30 días)',
      'One Zone-IA: 99.5% availability, 1 AZ, 20% más barato — datos reproducibles',
      'Intelligent-Tiering: mueve automáticamente entre tiers según acceso',
      'Glacier Instant: acceso en milisegundos — archiving con acceso ocasional',
      'Glacier Flexible: 1-12 horas retrieval — bulk option más barato',
      'Glacier Deep Archive: 12-48 horas — más barato de S3, 7-10 años retention',
    ],
    examTips: [
      'Minimum storage duration: Standard-IA 30 días, Glacier 90 días, Deep Archive 180 días',
      '"Infrequently accessed + available immediately" → Standard-IA o Glacier Instant',
      '"Compliance + 7 years" → Deep Archive con Vault Lock',
    ],
    awsServices: ['S3', 'S3 Glacier'],
    confusedWith: ['s3-lifecycle'],
  },
  {
    slug: 's3-replication',
    name: 'Replicación S3 (CRR y SRR)',
    description: 'Cross-Region Replication y Same-Region Replication para compliance y DR',
    domainSlug: 'resilient-architecture',
    topicSlug: 'storage-resilience',
    difficulty: 0.6,
    keyFacts: [
      'CRR (Cross-Region): compliance, latencia baja para usuarios globales, DR',
      'SRR (Same-Region): aggregation de logs, replicación prod→staging en misma región',
      'Versionado OBLIGATORIO en bucket origen y destino',
      'Solo replica objetos NUEVOS después de activar (no retroactivo sin Batch Replication)',
      'Delete markers NO se replican por default (configurable)',
      'Replication Time Control (RTC): SLA 99.99% en 15 minutos',
    ],
    examTips: [
      '"DR en otra región" → CRR + RTC para tiempo garantizado',
      '"Audit logs centralizados" → SRR para agregar múltiples buckets',
      'Objetos cifrados con SSE-KMS requieren configuración extra de key policy',
    ],
    awsServices: ['S3', 'KMS'],
    confusedWith: ['s3-lifecycle'],
  },
  {
    slug: 's3-lifecycle',
    name: 'S3 Lifecycle Policies',
    description: 'Reglas para transicionar y expirar objetos automáticamente entre storage classes',
    domainSlug: 'cost-optimized-architecture',
    topicSlug: 'cost-storage',
    difficulty: 0.4,
    keyFacts: [
      'Transition actions: mover objetos a otra clase después de N días',
      'Expiration actions: eliminar objetos o versiones no actuales',
      'Mínimo 30 días en Standard antes de transicionar a Standard-IA o One Zone-IA',
      'S3 Analytics ayuda a identificar patrones de acceso para configurar lifecycle',
      'Puedes filtrar por prefix, tags o tamaño de objeto',
    ],
    examTips: [
      '"Move to Glacier after 90 days" → Lifecycle rule: Transition to Glacier after 90d',
      '"Delete incomplete multipart uploads" → Lifecycle rule con AbortIncompleteMultipartUpload',
      'Se pueden combinar CRR + Lifecycle en el mismo bucket',
    ],
    awsServices: ['S3'],
    confusedWith: ['s3-storage-classes', 's3-replication'],
  },
  {
    slug: 's3-security',
    name: 'Seguridad S3',
    description: 'Bucket policies, ACLs, Block Public Access, cifrado SSE-S3/SSE-KMS/SSE-C/DSSE-KMS',
    domainSlug: 'secure-architecture',
    topicSlug: 'data-protection',
    difficulty: 0.6,
    keyFacts: [
      'Block Public Access: setting de cuenta y bucket — tiene precedencia sobre bucket policy',
      'Bucket Policy: basada en recursos, permite/denegar acceso granular por ARN',
      'SSE-S3: AWS gestiona claves (AES-256), sin costo extra',
      'SSE-KMS: claves en KMS, auditable, más caro (API calls)',
      'SSE-C: cliente provee y gestiona la clave',
      'DSSE-KMS: doble capa cifrado KMS — requisitos de seguridad más estrictos',
      'S3 Object Lock: WORM — governance mode vs compliance mode',
    ],
    examTips: [
      '"Audit who accessed key" → SSE-KMS (CloudTrail integrado)',
      '"Client manages key outside AWS" → SSE-C',
      '"Prevent deletion for compliance" → S3 Object Lock + Compliance mode',
      'MFA Delete: requiere MFA para eliminar versiones o deshabilitar versionado',
    ],
    awsServices: ['S3', 'KMS', 'CloudTrail', 'IAM'],
    confusedWith: ['kms-encryption', 'iam-fundamentals'],
  },
  // ---- RDS ----
  {
    slug: 'rds-multi-az',
    name: 'RDS Multi-AZ',
    description: 'Replicación síncrona en standby AZ para alta disponibilidad — automático failover',
    domainSlug: 'resilient-architecture',
    topicSlug: 'database-resilience',
    difficulty: 0.5,
    keyFacts: [
      'Replicación SÍNCRONA al standby en otra AZ',
      'Failover automático en 1-2 minutos (CNAME flip)',
      'El standby NO sirve tráfico de lectura (Multi-AZ ≠ Read Replica)',
      'Multi-AZ Multi-Standby (nuevo): hasta 3 standby en distintas AZ',
      'Backup se toma del standby para no impactar producción',
      'Soportado en: MySQL, PostgreSQL, Oracle, SQL Server, MariaDB',
    ],
    examTips: [
      '"High availability" + "automatic failover" → Multi-AZ',
      '"Scale read traffic" → Read Replicas (no Multi-AZ)',
      '"Zero RPO" → Multi-AZ (síncrono)',
      'Multi-AZ no previene pérdida de datos en errores lógicos (bugs, DELETE accidental)',
    ],
    awsServices: ['RDS', 'Route 53'],
    confusedWith: ['rds-read-replicas', 'aurora-global'],
  },
  {
    slug: 'rds-read-replicas',
    name: 'RDS Read Replicas',
    description: 'Réplicas asíncronas de solo lectura para escalar consultas y reducir carga en primary',
    domainSlug: 'performant-architecture',
    topicSlug: 'performance-database',
    difficulty: 0.5,
    keyFacts: [
      'Replicación ASÍNCRONA — puede haber lag (eventual consistency)',
      'Hasta 15 réplicas (Aurora) o 5 (RDS)',
      'Puede estar en otra región (Cross-Region Read Replica)',
      'Puede promocionarse a instancia standalone (útil para DR)',
      'Conexión diferente endpoint — aplicación debe enrutarse explícitamente',
      'Para MySQL/PostgreSQL, cross-region genera costo de data transfer',
    ],
    examTips: [
      '"Reporting queries slow down production" → Read Replica para reporting',
      '"RPO minutes" en otra región → Cross-Region Read Replica',
      'Para analytics heavy → Redshift, no Read Replica',
    ],
    awsServices: ['RDS', 'Aurora'],
    confusedWith: ['rds-multi-az', 'aurora-global'],
  },
  {
    slug: 'aurora-global',
    name: 'Aurora Global Database',
    description: 'Replicación global de Aurora con < 1 segundo de lag para DR activo-pasivo',
    domainSlug: 'resilient-architecture',
    topicSlug: 'database-resilience',
    difficulty: 0.7,
    keyFacts: [
      '1 región primary (escrituras), hasta 5 regiones secundarias (lecturas)',
      'Lag típico < 1 segundo entre regiones',
      'Failover manual a secundaria en < 1 minuto (Managed Planned Failover)',
      'Write Forwarding: las réplicas pueden reenviar escrituras al primary',
      'Hasta 16 Read Replicas por región secundaria',
      'RPO 1 segundo, RTO < 1 minuto con Managed Failover',
    ],
    examTips: [
      '"Global users low latency reads" → Aurora Global',
      '"Sub-second RPO cross-region" → Aurora Global vs RDS Cross-Region (lag segundos)',
      '"CRDR" (Cross-Region Disaster Recovery) → Aurora Global Database',
    ],
    awsServices: ['Aurora', 'Route 53'],
    confusedWith: ['rds-read-replicas', 'rds-multi-az'],
  },
  {
    slug: 'elasticache',
    name: 'ElastiCache (Redis y Memcached)',
    description: 'Caché in-memory para reducir latencia de BD y mejorar rendimiento de aplicaciones',
    domainSlug: 'performant-architecture',
    topicSlug: 'performance-database',
    difficulty: 0.6,
    keyFacts: [
      'Redis: persistencia opcional, estructuras de datos complejas, pub/sub, Multi-AZ, clustering',
      'Memcached: puro caché, multi-threaded, sin persistencia, sin replicación',
      'Lazy Loading: cache miss → lee de BD → carga caché',
      'Write Through: escribe en BD y caché simultáneamente',
      'Redis Cluster: sharding automático, hasta 500 nodos',
      'Redis AUTH + TLS en tránsito, cifrado en reposo',
    ],
    examTips: [
      '"Session store" → Redis (persistencia)',
      '"Simple caching sin estado" → Memcached (más barato)',
      '"Leaderboard, sorted sets" → Redis ZSET',
      '"RDS is slow" → ElastiCache entre app y RDS',
    ],
    awsServices: ['ElastiCache', 'RDS', 'DynamoDB'],
    confusedWith: ['rds-multi-az'],
  },
  // ---- VPC ----
  {
    slug: 'vpc-fundamentals',
    name: 'VPC Fundamentos',
    description: 'Subnets públicas/privadas, Internet Gateway, NAT Gateway, Route Tables y NACLs vs Security Groups',
    domainSlug: 'secure-architecture',
    topicSlug: 'network-security',
    difficulty: 0.5,
    keyFacts: [
      'CIDR /16 hasta /28 — /16 más grande (65,534 IPs usables)',
      'AWS reserva 5 IPs por subnet: .0 network, .1 router, .2 DNS, .3 futuro, último broadcast',
      'Internet Gateway: permite acceso a internet, stateful para instancias con public IP',
      'NAT Gateway: permite salida de subnets privadas sin exponer IPs privadas',
      'Security Groups: stateful, solo allow rules, aplica a instancias',
      'NACLs: stateless, allow + deny, aplica a subnets, se evalúan en orden',
      'Flow Logs: captura metadata de tráfico IP para análisis y troubleshooting',
    ],
    examTips: [
      '"Block specific IP" → NACL (deny rule), Security Groups no tienen deny',
      '"Private subnet accesa internet" → NAT Gateway (no Internet Gateway)',
      '"Redundant NAT" → NAT Gateway por AZ (no es cross-AZ automático)',
    ],
    awsServices: ['VPC', 'NAT Gateway', 'Internet Gateway', 'Flow Logs'],
    confusedWith: ['vpc-endpoints', 'transit-gateway'],
  },
  {
    slug: 'vpc-endpoints',
    name: 'VPC Endpoints (Gateway y Interface)',
    description: 'Conexión privada a servicios AWS sin traversar internet público',
    domainSlug: 'secure-architecture',
    topicSlug: 'network-security',
    difficulty: 0.7,
    keyFacts: [
      'Gateway Endpoint: SOLO S3 y DynamoDB, gratuito, modifica Route Table',
      'Interface Endpoint (PrivateLink): casi todos los servicios, costo por hora + GB, crea ENI',
      'Gateway Endpoint no requiere DNS, Interface Endpoint sí (Private DNS)',
      'Endpoint Policy: controla qué acciones se pueden hacer en el endpoint',
      'Interface Endpoint disponible en múltiples AZ para HA',
    ],
    examTips: [
      '"S3 desde subnet privada sin internet" → Gateway Endpoint (gratis)',
      '"KMS desde subnet privada" → Interface Endpoint (PrivateLink)',
      '"Evitar costo NAT Gateway para S3" → Gateway Endpoint S3',
    ],
    awsServices: ['VPC', 'S3', 'DynamoDB', 'PrivateLink'],
    confusedWith: ['vpc-fundamentals', 'vpc-peering'],
  },
  {
    slug: 'vpc-peering',
    name: 'VPC Peering',
    description: 'Conexión punto a punto entre dos VPCs con routing privado, no transitivo',
    domainSlug: 'resilient-architecture',
    topicSlug: 'networking-connectivity',
    difficulty: 0.6,
    keyFacts: [
      'NO es transitivo: A-B y B-C peered, pero A no puede hablar con C',
      'CIDRs no pueden solaparse',
      'Funciona inter-región y cross-account',
      'Requiere actualizar Route Tables en ambas VPCs',
      'No hay ancho de banda límite (usa AWS backbone)',
      'Con muchas VPCs → Transit Gateway es más escalable que full-mesh peering',
    ],
    examTips: [
      '"5 VPCs interconnected" → Transit Gateway > peering full-mesh (N²/2 conexiones)',
      '"Transitive routing" → NO posible con VPC Peering',
      '"Share services to many VPCs" → PrivateLink (más seguro que peering)',
    ],
    awsServices: ['VPC', 'Transit Gateway'],
    confusedWith: ['transit-gateway', 'direct-connect'],
  },
  {
    slug: 'transit-gateway',
    name: 'Transit Gateway (TGW)',
    description: 'Hub central para conectar múltiples VPCs, cuentas y redes on-premises',
    domainSlug: 'resilient-architecture',
    topicSlug: 'networking-connectivity',
    difficulty: 0.7,
    keyFacts: [
      'Hub and spoke: reemplaza full-mesh de VPC Peering',
      'Soporta routing transitivo (a diferencia de VPC Peering)',
      'Puede conectar Direct Connect, Site-to-Site VPN y VPCs',
      'Transit Gateway Peering: conectar TGWs de distintas regiones',
      'Route Tables en TGW: controla qué pueden ver entre sí',
      'Multicast support: útil para streaming financiero',
    ],
    examTips: [
      '"Multiple VPCs + on-premises + centralized routing" → Transit Gateway',
      '"Shared services VPC (security, DNS)" → TGW con attachment',
      'TGW tiene costo por attachment + por GB transferido',
    ],
    awsServices: ['Transit Gateway', 'VPC', 'Direct Connect', 'VPN'],
    confusedWith: ['vpc-peering', 'direct-connect'],
  },
  {
    slug: 'direct-connect',
    name: 'AWS Direct Connect',
    description: 'Conexión dedicada de red privada desde on-premises a AWS, bajo latencia y ancho de banda consistente',
    domainSlug: 'resilient-architecture',
    topicSlug: 'networking-connectivity',
    difficulty: 0.7,
    keyFacts: [
      'Conexión física dedicada, 1 Gbps a 100 Gbps',
      'No pasa por internet público — latencia predecible',
      'Direct Connect Gateway: conecta mismo DX a múltiples regiones/VPCs',
      'Setup toma semanas (physical provisioning)',
      'Para backup de DX usar Site-to-Site VPN (más barato)',
      'Hosted Connection: compartida (50 Mbps - 10 Gbps) via APN partners',
    ],
    examTips: [
      '"Consistent bandwidth, low latency to on-premises" → Direct Connect',
      '"DX redundancy" → segundo circuito DX o Site-to-Site VPN como backup',
      '"Immediate connectivity" → VPN (DX tarda semanas)',
    ],
    awsServices: ['Direct Connect', 'VPN', 'Transit Gateway'],
    confusedWith: ['transit-gateway', 'vpc-peering'],
  },
  // ---- IAM ----
  {
    slug: 'iam-fundamentals',
    name: 'IAM Fundamentos',
    description: 'Users, Groups, Roles, Policies (Identity vs Resource based) y el principio de mínimo privilegio',
    domainSlug: 'secure-architecture',
    topicSlug: 'iam-identity',
    difficulty: 0.4,
    keyFacts: [
      'Identity-based policies: adjuntas a users/groups/roles',
      'Resource-based policies: adjuntas al recurso (S3 bucket policy, SQS queue policy)',
      'Evaluation logic: explicit DENY > explicit ALLOW > implicit DENY',
      'IAM Roles para servicios: EC2 instance profile, Lambda execution role',
      'Conditions: permitir acceso basado en IP, MFA, time, tags',
      'Permissions Boundary: límite máximo de permisos (no otorga permisos por sí solo)',
    ],
    examTips: [
      '"Cross-account access" → IAM Role con trust policy (no users)',
      '"Service needs to access S3" → IAM Role (no access keys hardcoded)',
      'Deny explícito siempre gana sobre cualquier Allow',
    ],
    awsServices: ['IAM', 'STS', 'Organizations'],
    confusedWith: ['iam-roles-vs-policies', 'scp-organizations'],
  },
  {
    slug: 'iam-roles-vs-policies',
    name: 'IAM Roles vs Policies',
    description: 'Cuándo usar Roles vs Policies, assume role, trust policies y cross-account access patterns',
    domainSlug: 'secure-architecture',
    topicSlug: 'iam-identity',
    difficulty: 0.6,
    keyFacts: [
      'Role: identidad temporal con trust policy + permission policy',
      'AssumeRole via STS: retorna temporary credentials (Access Key + Secret + Token)',
      'Instance Profile: wrapper para adjuntar role a EC2',
      'Cross-account: Account A asume role en Account B via STS',
      'External ID: para casos de confused deputy problem en third-party',
      'Session tags: contexto adicional en las credenciales temporales',
    ],
    examTips: [
      '"On-premises necesita acceso a AWS" → IAM Role + AssumeRole (no usuarios IAM)',
      '"Third party integración" → Role con External ID (confused deputy)',
      '"Temporary credentials" → STS AssumeRole',
    ],
    awsServices: ['IAM', 'STS', 'EC2 Instance Profile'],
    confusedWith: ['iam-fundamentals', 'cognito'],
  },
  {
    slug: 'scp-organizations',
    name: 'SCPs y AWS Organizations',
    description: 'Service Control Policies como guardrails preventivos en multi-account setup',
    domainSlug: 'secure-architecture',
    topicSlug: 'iam-identity',
    difficulty: 0.7,
    keyFacts: [
      'SCP no otorga permisos, solo limita el máximo posible en la cuenta',
      'Aplica a todos los principals EXCEPTO Management Account',
      'SCPs + IAM policies: el efectivo es la intersección',
      'Herencia: SCP aplica a la OU y todos sus hijos (accounts)',
      'Use cases: deny cambiar region, deny salir de Org, deny crear IAM users',
      'Service Control Policies (preventive) vs Config Rules (detective)',
    ],
    examTips: [
      '"Prevent any user including admin from disabling CloudTrail" → SCP (no IAM)',
      '"Restrict to approved regions" → SCP DenyAllOutside...',
      'SCP no aplica al Management Account — usar con cuidado',
    ],
    awsServices: ['AWS Organizations', 'SCP', 'CloudTrail', 'Config'],
    confusedWith: ['iam-fundamentals', 'iam-roles-vs-policies'],
  },
  {
    slug: 'cognito',
    name: 'Amazon Cognito',
    description: 'User Pools (autenticación) y Identity Pools (autorización AWS) para aplicaciones web/mobile',
    domainSlug: 'secure-architecture',
    topicSlug: 'iam-identity',
    difficulty: 0.7,
    keyFacts: [
      'User Pool: directorio de usuarios (signup/signin, MFA, social login)',
      'Identity Pool (Federated Identities): cambia token de User Pool por credenciales AWS temporales',
      'User Pool retorna JWT tokens (ID, Access, Refresh)',
      'Identity Pool usa STS AssumeRoleWithWebIdentity internamente',
      'Puede federar con SAML 2.0, OIDC providers, social (Google, Facebook)',
      'Hosted UI: página de login lista para usar, customizable',
    ],
    examTips: [
      '"Mobile app users access S3 directly" → Cognito Identity Pool (credenciales temporales)',
      '"Web app login/signup" → Cognito User Pool',
      '"SSO con AD corporativo" → User Pool + SAML IdP',
    ],
    awsServices: ['Cognito', 'IAM', 'STS', 'API Gateway'],
    confusedWith: ['iam-roles-vs-policies'],
  },
  // ---- Security ----
  {
    slug: 'kms-encryption',
    name: 'AWS KMS',
    description: 'Gestión de claves de cifrado, Customer Managed Keys vs AWS Managed Keys, KMS envelope encryption',
    domainSlug: 'secure-architecture',
    topicSlug: 'data-protection',
    difficulty: 0.7,
    keyFacts: [
      'Customer Managed Key (CMK): control total de rotación, policy, eliminación (7-30 días pendiente)',
      'AWS Managed Key: gestionada por AWS para el servicio, rotación automática anual',
      'AWS Owned Key: interna de AWS, sin visibilidad para el cliente',
      'Envelope Encryption: KMS cifra Data Encryption Key (DEK), DEK cifra datos',
      'KMS tiene límite de 4KB por encrypt/decrypt — para datos grandes usar envelope',
      'Multi-Region Keys: replicar CMK a otras regiones para DR/global',
    ],
    examTips: [
      '"Audit every key usage" → CMK + CloudTrail',
      '"Encrypt > 4KB with KMS" → GenerateDataKey + envelope encryption',
      '"Copy encrypted AMI cross-region" → Multi-Region Key o re-encrypt en destino',
    ],
    awsServices: ['KMS', 'CloudTrail', 'S3', 'EBS', 'RDS'],
    confusedWith: ['secrets-manager', 's3-security'],
  },
  {
    slug: 'secrets-manager',
    name: 'AWS Secrets Manager',
    description: 'Almacenamiento seguro y rotación automática de secrets, credenciales de BD y API keys',
    domainSlug: 'secure-architecture',
    topicSlug: 'data-protection',
    difficulty: 0.5,
    keyFacts: [
      'Rotación automática con Lambda — para RDS, Redshift, DocumentDB nativo',
      'Cross-account access con resource-based policy',
      'Cifrado con KMS obligatorio',
      'Parameter Store (SSM): más barato, sin rotación automática nativa',
      'Secrets Manager: $0.40/secret/mes — más caro pero más features',
      'Caching client-side para reducir API calls',
    ],
    examTips: [
      '"Automatic rotation of DB credentials" → Secrets Manager (no Parameter Store)',
      '"Store configuration parameters" → Parameter Store (más barato)',
      '"Share secrets cross-account" → Secrets Manager con resource policy',
    ],
    awsServices: ['Secrets Manager', 'KMS', 'Lambda', 'RDS'],
    confusedWith: ['kms-encryption'],
  },
  {
    slug: 'shield-waf',
    name: 'AWS Shield y WAF',
    description: 'Shield Standard/Advanced para DDoS, WAF para filtrado de tráfico HTTP/HTTPS a nivel L7',
    domainSlug: 'secure-architecture',
    topicSlug: 'network-security',
    difficulty: 0.6,
    keyFacts: [
      'Shield Standard: gratuito, automático para todos — protege L3/L4 DDoS',
      'Shield Advanced: $3,000/mes, protege CloudFront, ALB, ELB, EC2, R53 — DRT team',
      'WAF: reglas para bloquear SQL injection, XSS, rate limiting, geo-blocking',
      'WAF WebACL: puede asociarse a CloudFront, ALB, API Gateway, AppSync',
      'AWS Managed Rules: OWASP Top 10, Amazon IP Reputation, Core Rule Set',
      'WAF + Shield Advanced: protección completa L3-L7',
    ],
    examTips: [
      '"Protect against OWASP Top 10" → WAF con Managed Rules',
      '"DDoS protection with cost protection" → Shield Advanced',
      '"Block requests from specific country" → WAF geo-match rule',
    ],
    awsServices: ['Shield', 'WAF', 'CloudFront', 'ALB'],
    confusedWith: ['vpc-fundamentals', 'security-hub'],
  },
  {
    slug: 'security-hub',
    name: 'AWS Security Hub',
    description: 'Vista centralizada de hallazgos de seguridad de múltiples servicios AWS y estándares de compliance',
    domainSlug: 'secure-architecture',
    topicSlug: 'network-security',
    difficulty: 0.5,
    keyFacts: [
      'Agrega findings de: GuardDuty, Inspector, Macie, Firewall Manager, Config',
      'Estándares: AWS Foundational Security, CIS, PCI DSS',
      'ASFF (Amazon Security Finding Format): formato normalizado',
      'Automated response: EventBridge → Lambda para remediación',
      'Multi-account via Organizations: management account ve todo',
    ],
    examTips: [
      '"Centralized security findings across accounts" → Security Hub',
      '"Detect sensitive data in S3" → Macie (luego Security Hub agrega)',
      '"Automated remediation of security findings" → Security Hub + EventBridge + Lambda',
    ],
    awsServices: ['Security Hub', 'GuardDuty', 'Macie', 'Inspector', 'Config'],
    confusedWith: ['shield-waf'],
  },
  // ---- Content Delivery ----
  {
    slug: 'cloudfront-caching',
    name: 'CloudFront y Caching',
    description: 'CDN global, edge caching, Origins, Behaviors, Cache Policies y Lambda@Edge',
    domainSlug: 'performant-architecture',
    topicSlug: 'content-delivery',
    difficulty: 0.6,
    keyFacts: [
      '400+ edge locations globales — reduce latencia al servir desde el edge',
      'Origin: S3, ALB, EC2, custom HTTP — con Origin Access Control (OAC) para S3',
      'Cache Policies: controlan TTL, headers y query strings que van al cache key',
      'Origin Request Policies: qué se forwarda al origin sin incluir en cache key',
      'Lambda@Edge: ejecuta Lambda en edge (us-east-1) — A/B testing, auth, rewrites',
      'CloudFront Functions: más barato, más limitado — header manipulation simple',
      'Signed URLs/Cookies: acceso a contenido restringido desde CloudFront',
    ],
    examTips: [
      '"Global static content" → CloudFront + S3 con OAC',
      '"Restrict S3 access only via CloudFront" → OAC + S3 bucket policy',
      '"Custom auth at edge" → Lambda@Edge (no CloudFront Functions para lógica compleja)',
    ],
    awsServices: ['CloudFront', 'S3', 'Lambda@Edge', 'ACM'],
    confusedWith: ['route53-routing', 'api-gateway'],
  },
  {
    slug: 'route53-routing',
    name: 'Route 53 Routing Policies',
    description: 'Simple, Weighted, Latency, Failover, Geolocation, Geoproximity y Multivalue routing',
    domainSlug: 'performant-architecture',
    topicSlug: 'content-delivery',
    difficulty: 0.7,
    keyFacts: [
      'Simple: un record, un valor — sin health checks para routing decisions',
      'Weighted: distribuir tráfico por porcentaje (A/B deployments)',
      'Latency: redirige al endpoint con menor latencia medida desde AWS',
      'Failover: Active/Passive con health checks obligatorios',
      'Geolocation: basado en ubicación geográfica del usuario (compliance)',
      'Geoproximity: como geolocation pero con bias para ajustar regiones',
      'Multivalue: como simple pero con health checks, hasta 8 valores',
    ],
    examTips: [
      '"Blue-green deployment gradual" → Weighted (100%→0 blue, 0%→100 green)',
      '"Serve legal content by country" → Geolocation',
      '"Active-passive DR" → Failover routing con health checks',
      '"Route to multiple IPs with health checks" → Multivalue (no simple)',
    ],
    awsServices: ['Route 53', 'CloudFront', 'ELB'],
    confusedWith: ['elb-types', 'cloudfront-caching'],
  },
  {
    slug: 'api-gateway',
    name: 'Amazon API Gateway',
    description: 'REST, HTTP y WebSocket APIs — throttling, caching, authorizers y VPC Link',
    domainSlug: 'performant-architecture',
    topicSlug: 'content-delivery',
    difficulty: 0.6,
    keyFacts: [
      'REST API: más features (usage plans, API keys, custom authorizers)',
      'HTTP API: más barato (70%), más simple — no soporta API keys nativo',
      'WebSocket API: comunicación bidireccional persistente',
      'Throttling: 10,000 RPS default por cuenta (ajustable)',
      'Caching: TTL configurable, key customizable',
      'Authorizers: Lambda (custom), Cognito User Pool, JWT',
      'VPC Link: conectar API Gateway a recursos privados en VPC (ALB, NLB)',
    ],
    examTips: [
      '"Serverless API with auth" → API Gateway + Lambda + Cognito authorizer',
      '"Private ALB exposed as API" → API Gateway + VPC Link',
      '"Cost-optimize API" → HTTP API (no REST) si no necesitas usage plans',
    ],
    awsServices: ['API Gateway', 'Lambda', 'Cognito', 'VPC'],
    confusedWith: ['cloudfront-caching', 'elb-types'],
  },
  {
    slug: 'elb-types',
    name: 'Elastic Load Balancing (ALB, NLB, GWLB)',
    description: 'Application (L7), Network (L4) y Gateway Load Balancer — cuándo usar cada uno',
    domainSlug: 'resilient-architecture',
    topicSlug: 'ec2-compute',
    difficulty: 0.6,
    keyFacts: [
      'ALB (L7): HTTP/HTTPS, path-based routing, host-based routing, WebSocket, gRPC',
      'NLB (L4): TCP/UDP, ultra-low latency (<1ms), static IP, Elastic IP',
      'GWLB (L3): transparente para network appliances (firewalls, IDS/IPS) — GENEVE protocol',
      'ALB + NLB = Application load balancing + static IP',
      'Cross-Zone Load Balancing: distribuye entre AZ (ALB siempre ON, NLB cobra extra)',
      'Access Logs + CloudWatch metrics para monitoring',
    ],
    examTips: [
      '"L7 routing by path/host" → ALB',
      '"Static IP / whitelisting" → NLB',
      '"Network inspection / firewall" → GWLB',
      '"gRPC microservices" → ALB (soporta HTTP/2)',
    ],
    awsServices: ['ALB', 'NLB', 'GWLB', 'EC2 Auto Scaling'],
    confusedWith: ['route53-routing', 'api-gateway'],
  },
  // ---- Messaging ----
  {
    slug: 'sqs-vs-sns-vs-eventbridge',
    name: 'SQS vs SNS vs EventBridge',
    description: 'Cuándo usar cola (SQS), fan-out (SNS) o event bus (EventBridge) para desacoplar sistemas',
    domainSlug: 'performant-architecture',
    topicSlug: 'messaging-integration',
    difficulty: 0.7,
    keyFacts: [
      'SQS: pull-based, 1 consumer por mensaje, retención 14 días, DLQ, visibility timeout',
      'SQS FIFO: exactamente-una-vez entrega, 300 TPS (con batching 3,000 TPS)',
      'SNS: push-based (pub/sub), fan-out a múltiples suscriptores',
      'SNS→SQS fan-out: patrón clásico para mensajería durable + distribución',
      'EventBridge: event bus, reglas de filtrado, cross-account, 90+ AWS sources',
      'EventBridge > SNS para routing complejo y event-driven con múltiples destinos',
    ],
    examTips: [
      '"Decouple application, ensure message not lost" → SQS',
      '"One message to multiple services" → SNS fan-out',
      '"React to AWS service events (CloudTrail, GuardDuty)" → EventBridge',
      '"Order matters, no duplicates" → SQS FIFO',
    ],
    awsServices: ['SQS', 'SNS', 'EventBridge', 'Lambda'],
    confusedWith: ['kinesis-streams-vs-firehose'],
  },
  {
    slug: 'kinesis-streams-vs-firehose',
    name: 'Kinesis Data Streams vs Firehose',
    description: 'Streaming de datos en tiempo real: cuándo procesar (Streams) vs cuándo entregar (Firehose)',
    domainSlug: 'performant-architecture',
    topicSlug: 'messaging-integration',
    difficulty: 0.7,
    keyFacts: [
      'Kinesis Data Streams: retención 24h-365d, múltiples consumers, bajo latencia (<1s)',
      'Shards: 1 MB/s entrada, 2 MB/s salida por shard',
      'Kinesis Firehose: entrega automática a S3, Redshift, OpenSearch, Splunk',
      'Firehose: near real-time (60s o 1MB buffer), sin código de consumer necesario',
      'Enhanced Fan-Out: 2MB/s per consumer per shard (HTTP/2 push)',
      'Kinesis Data Analytics (Flink): SQL queries en streams en tiempo real',
    ],
    examTips: [
      '"Ingest logs to S3 without coding" → Firehose',
      '"Real-time processing with multiple consumers" → Kinesis Data Streams',
      '"ClickStream analytics in real-time" → KDS + Kinesis Analytics',
    ],
    awsServices: ['Kinesis', 'Firehose', 'S3', 'Lambda', 'Redshift'],
    confusedWith: ['sqs-vs-sns-vs-eventbridge'],
  },
  {
    slug: 'lambda-patterns',
    name: 'Lambda Patterns y Límites',
    description: 'Event sources, concurrencia, cold starts, layers, invocation types y límites importantes',
    domainSlug: 'performant-architecture',
    topicSlug: 'containers-serverless',
    difficulty: 0.6,
    keyFacts: [
      'Timeout máximo: 15 minutos',
      'Memory: 128 MB - 10 GB (CPU escala proporcionalmente)',
      'Ephemeral storage /tmp: 512 MB - 10 GB',
      'Concurrencia default: 1,000 por región (ajustable)',
      'Reserved concurrency: garantiza capacidad, limita máximo',
      'Provisioned concurrency: elimina cold starts (pre-warming)',
      'Layers: hasta 5, max 250 MB total desplegado',
      'Synchronous (API Gateway), Async (S3, SNS), Stream (SQS, Kinesis)',
    ],
    examTips: [
      '"Eliminate cold starts" → Provisioned Concurrency',
      '"Throttle Lambda to protect downstream" → Reserved Concurrency con limit bajo',
      '"Long-running task >15min" → Lambda no sirve → ECS/Fargate o Step Functions',
    ],
    awsServices: ['Lambda', 'API Gateway', 'SQS', 'EventBridge', 'Step Functions'],
    confusedWith: ['ecs-vs-eks-vs-fargate'],
  },
  // ---- Containers ----
  {
    slug: 'ecs-vs-eks-vs-fargate',
    name: 'ECS vs EKS vs Fargate',
    description: 'Cuándo usar ECS (simplicity), EKS (Kubernetes), y Fargate (serverless containers)',
    domainSlug: 'performant-architecture',
    topicSlug: 'containers-serverless',
    difficulty: 0.7,
    keyFacts: [
      'ECS: orquestación de contenedores AWS-native, Task Definitions, Service',
      'ECS on EC2: tú gestionas las instancias del cluster',
      'ECS on Fargate: serverless, sin gestión de infraestructura',
      'EKS: Kubernetes administrado, compatible con k8s ecosystem, más complejo',
      'EKS Fargate: pods k8s serverless, sin nodos que gestionar',
      'ECR: registro de imágenes Docker privado, integrado con IAM',
      'App Mesh: service mesh para ECS/EKS — mTLS, observabilidad',
    ],
    examTips: [
      '"Kubernetes requirement" → EKS',
      '"Simple containers, AWS-native" → ECS',
      '"No infraestructura que gestionar" → Fargate (ECS o EKS)',
      '"Spot para containers cost-optimized" → ECS on Spot Instances',
    ],
    awsServices: ['ECS', 'EKS', 'Fargate', 'ECR', 'ALB'],
    confusedWith: ['lambda-patterns'],
  },
  {
    slug: 'cloudformation-vs-cdk',
    name: 'CloudFormation vs CDK',
    description: 'IaC con CloudFormation (JSON/YAML) y CDK (TypeScript/Python) — cuándo usar cada uno',
    domainSlug: 'resilient-architecture',
    topicSlug: 'ec2-compute',
    difficulty: 0.5,
    keyFacts: [
      'CloudFormation: declarativo, JSON/YAML, cambios via Change Sets',
      'CDK: genera CloudFormation, lógica en código real (loops, conditions)',
      'Stacks: unidad de despliegue en CloudFormation, con rollback automático',
      'StackSets: desplegar mismo stack en múltiples cuentas/regiones',
      'Drift Detection: detectar cambios manuales vs template',
      'Nested Stacks: reutilizar templates, separar preocupaciones',
    ],
    examTips: [
      '"Deploy across 50 accounts and 3 regions" → CloudFormation StackSets',
      '"Detect manual changes" → CloudFormation Drift Detection',
      'CDK → CloudFormation siempre (CDK no es alternativa, es wrapper)',
    ],
    awsServices: ['CloudFormation', 'CDK', 'Organizations'],
    confusedWith: ['ecs-vs-eks-vs-fargate'],
  },
  // ---- Cost ----
  {
    slug: 'cost-optimization-strategies',
    name: 'Estrategias de Optimización de Costos',
    description: 'Right-sizing, Savings Plans, Reserved Instances, Spot, arquitecturas serverless y herramientas de análisis',
    domainSlug: 'cost-optimized-architecture',
    topicSlug: 'cost-governance',
    difficulty: 0.5,
    keyFacts: [
      'Right-sizing: ajustar instancias al uso real (Compute Optimizer)',
      'Savings Plans > Reserved Instances en flexibilidad',
      'Spot Instances: hasta 90% ahorro para workloads tolerantes a interrupciones',
      'S3 Lifecycle: mover datos a clases más baratas automáticamente',
      'Data Transfer: mismo AZ sin costo, cross-AZ $0.01/GB, internet varia',
      'AWS Cost Explorer: análisis histórico + forecast',
      'Budgets: alertas cuando se supera un umbral',
    ],
    examTips: [
      '"Analyze which instances to downsize" → Compute Optimizer',
      '"Reduce data transfer costs" → Same AZ communication + VPC Endpoints',
      '"Batch processing cost-optimized" → Spot Fleet con Spot Instances',
    ],
    awsServices: ['Cost Explorer', 'Budgets', 'Compute Optimizer', 'Trusted Advisor'],
    confusedWith: ['ec2-pricing-models'],
  },
  {
    slug: 'trusted-advisor',
    name: 'AWS Trusted Advisor',
    description: '5 pilares de recomendaciones: Cost, Performance, Security, Fault Tolerance, Service Limits',
    domainSlug: 'cost-optimized-architecture',
    topicSlug: 'cost-governance',
    difficulty: 0.4,
    keyFacts: [
      '5 categorías: Cost Optimization, Performance, Security, Fault Tolerance, Service Limits',
      'Business/Enterprise Support: acceso a todas las verificaciones',
      'Gratis: 7 checks básicos (S3 public buckets, IAM use, MFA on root)',
      'Trusted Advisor + EventBridge: alertas automáticas en cambios de estado',
      'Refresh: cada semana automático, manual via API',
    ],
    examTips: [
      '"Check unused Reserved Instances" → Trusted Advisor (Cost category)',
      '"Identify security vulnerabilities" → Trusted Advisor Security + GuardDuty + Security Hub',
      '"Service limit alerts" → Trusted Advisor + EventBridge',
    ],
    awsServices: ['Trusted Advisor', 'EventBridge', 'SNS'],
    confusedWith: ['security-hub', 'cost-optimization-strategies'],
  },
]

export function getConceptBySlug(slug: string): ConceptDefinition | undefined {
  return CONCEPTS.find(c => c.slug === slug)
}

export function getConceptsByDomain(domainSlug: string): ConceptDefinition[] {
  return CONCEPTS.filter(c => c.domainSlug === domainSlug)
}

export function getDomainBySlug(slug: string): DomainDefinition | undefined {
  return DOMAINS.find(d => d.slug === slug)
}

export function getTopicsByDomain(domainSlug: string): TopicDefinition[] {
  return TOPICS.filter(t => t.domainSlug === domainSlug)
}
