/**
 * Sample SAA-C03 mock-exam data shared between the exam and results pages.
 *
 * Eight questions covering the four official domains. Each question has
 * one correct answer and a single-paragraph explanation. In production
 * this data is generated by the question engine (lib/question-engine).
 */

export interface ExamOption {
  label: 'A' | 'B' | 'C' | 'D'
  text: string
}

export interface ExamQuestion {
  id: number
  domain:
    | 'Resilient'
    | 'High-performing'
    | 'Secure'
    | 'Cost-optimized'
  prompt: string
  options: ExamOption[]
  correct: 'A' | 'B' | 'C' | 'D'
  explanation: string
}

export const EXAM_META = {
  code: 'SAA-C03',
  name: 'Solutions Architect Associate · Mock #5',
  totalMinutes: 130,
  passingScore: 720,
  totalQuestions: 65,
}

// 8-question sample (the visible slice of a 65-question mock).
export const QUESTIONS: ExamQuestion[] = [
  {
    id: 1,
    domain: 'Resilient',
    prompt:
      'A retail company runs a stateless web application on EC2 instances behind an Application Load Balancer in a single AZ. Traffic is unpredictable; outages during AZ failures are unacceptable. Which change provides the highest availability with the least operational overhead?',
    options: [
      { label: 'A', text: 'Add more EC2 instances in the same AZ behind the existing ALB.' },
      { label: 'B', text: 'Place the EC2 instances in an Auto Scaling group spanning multiple AZs and attach them to a multi-AZ ALB.' },
      { label: 'C', text: 'Move the workload to a single larger instance type with enhanced networking.' },
      { label: 'D', text: 'Deploy a second ALB in a different AZ and round-robin DNS between the two.' },
    ],
    correct: 'B',
    explanation:
      "Auto Scaling across multiple AZs combined with a multi-AZ ALB is the canonical AWS pattern for AZ-fault tolerance. Round-robin DNS doesn't react to failure fast enough; vertical scaling doesn't help with AZ outages.",
  },
  {
    id: 2,
    domain: 'Secure',
    prompt:
      "An application running on EC2 needs to read objects from a private S3 bucket. The security team requires that no long-lived credentials touch the instance. What's the right approach?",
    options: [
      { label: 'A', text: 'Store an IAM user access key on the instance and rotate it weekly via cron.' },
      { label: 'B', text: 'Use an IAM role attached to the EC2 instance profile.' },
      { label: 'C', text: 'Embed an STS-issued token in the AMI and refresh on launch.' },
      { label: 'D', text: 'Store credentials in Systems Manager Parameter Store and pull at boot.' },
    ],
    correct: 'B',
    explanation:
      'Instance profiles let EC2 obtain temporary credentials from STS automatically — no long-lived keys ever touch the instance. The other options either store secrets on the instance or embed them in immutable artifacts.',
  },
  {
    id: 3,
    domain: 'Cost-optimized',
    prompt:
      "A nightly batch job runs for two hours on m5.4xlarge instances. The job is fault-tolerant and can be restarted from checkpoints. Cost is the priority. Which purchase option fits best?",
    options: [
      { label: 'A', text: 'On-Demand instances.' },
      { label: 'B', text: 'Standard Reserved Instances with a 3-year term.' },
      { label: 'C', text: 'Spot Instances.' },
      { label: 'D', text: 'Dedicated Hosts.' },
    ],
    correct: 'C',
    explanation:
      'Fault-tolerant, restartable workloads are textbook Spot candidates — up to 90% cheaper than On-Demand. Reserved Instances suit predictable, always-on capacity; Dedicated Hosts solve a different (compliance) problem.',
  },
  {
    id: 4,
    domain: 'High-performing',
    prompt:
      'A globally distributed user base reads largely static content from an origin in eu-west-1. Latency for users in Asia-Pacific is poor. What is the simplest improvement?',
    options: [
      { label: 'A', text: 'Add Auto Scaling to the origin.' },
      { label: 'B', text: 'Front the origin with a CloudFront distribution.' },
      { label: 'C', text: 'Replicate the origin to ap-southeast-1 and use Route 53 latency routing.' },
      { label: 'D', text: 'Increase the EC2 instance size in the origin region.' },
    ],
    correct: 'B',
    explanation:
      "CloudFront caches at 600+ edge locations so requests are served from the closest POP — exactly the cure for cross-region latency on largely static content. Replicating the origin is correct but heavier; Auto Scaling and bigger instances don't address geography.",
  },
  {
    id: 5,
    domain: 'Resilient',
    prompt:
      "A microservice needs to publish events that may be consumed by multiple downstream services, some of which can be offline for short periods. Which messaging service fits best?",
    options: [
      { label: 'A', text: 'Amazon SQS Standard queue per consumer.' },
      { label: 'B', text: 'Amazon SNS topic with one subscription per consumer.' },
      { label: 'C', text: 'Amazon Kinesis Data Streams.' },
      { label: 'D', text: 'Amazon EventBridge with a single bus.' },
    ],
    correct: 'D',
    explanation:
      "EventBridge is designed for event-driven architectures with multiple targets and built-in retry/replay semantics. SNS fan-out is a valid alternative but EventBridge adds schema registry, content filtering, and archive/replay — closer to what the prompt's pattern requires.",
  },
  {
    id: 6,
    domain: 'Secure',
    prompt:
      "An RDS Aurora cluster contains PII subject to GDPR. Audit requires that database backups remain encrypted at rest with keys the customer controls and can rotate. Which configuration meets the requirement?",
    options: [
      { label: 'A', text: 'Enable RDS encryption with the default AWS-managed KMS key.' },
      { label: 'B', text: 'Enable RDS encryption with a customer-managed KMS key (CMK).' },
      { label: 'C', text: 'Disable RDS encryption and use S3 server-side encryption on exports.' },
      { label: 'D', text: 'Use TDE (Transparent Data Encryption) at the application layer.' },
    ],
    correct: 'B',
    explanation:
      'Customer-managed KMS keys are the only option that gives you full control of key policy, rotation, and access logs. AWS-managed keys are encrypted-at-rest but the customer cannot rotate or restrict them per the audit requirement.',
  },
  {
    id: 7,
    domain: 'High-performing',
    prompt:
      "A read-heavy application using RDS PostgreSQL is experiencing CPU saturation on the primary during peak hours. The workload is 90% reads. What's the most efficient fix?",
    options: [
      { label: 'A', text: 'Vertically scale the primary to a larger instance class.' },
      { label: 'B', text: 'Add up to 5 RDS read replicas and route read traffic to them.' },
      { label: 'C', text: 'Migrate to DynamoDB.' },
      { label: 'D', text: 'Enable Multi-AZ on the primary.' },
    ],
    correct: 'B',
    explanation:
      "Read replicas offload read traffic and scale horizontally — exactly the pattern for a 90%-read workload. Multi-AZ provides HA but the standby doesn't serve traffic. Migrating engines is overkill for a CPU bottleneck.",
  },
  {
    id: 8,
    domain: 'Cost-optimized',
    prompt:
      "An archive of compliance documents must be retained for 7 years. Documents are accessed less than once per year for ad-hoc audits, with retrieval times of up to 12 hours acceptable. Which storage class is most cost-effective?",
    options: [
      { label: 'A', text: 'S3 Standard.' },
      { label: 'B', text: 'S3 Standard-Infrequent Access.' },
      { label: 'C', text: 'S3 Glacier Flexible Retrieval.' },
      { label: 'D', text: 'S3 Glacier Deep Archive.' },
    ],
    correct: 'D',
    explanation:
      'Deep Archive is the cheapest S3 tier and is designed for data accessed less than once per year with retrieval times of 12+ hours — exactly the prompt. Flexible Retrieval is cheaper than IA but more expensive than Deep Archive.',
  },
]

// Pretend results — what the user "scored" when they came back to the
// results page. In production this is computed from question_attempts.
export const SAMPLE_RESULTS: Record<number, 'A' | 'B' | 'C' | 'D' | null> = {
  1: 'B',
  2: 'B',
  3: 'C',
  4: 'B',
  5: 'A',
  6: 'A',
  7: 'B',
  8: 'D',
}

export const SAMPLE_FLAGGED = new Set<number>([5, 6])
