import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
} from '@react-email/components'
import * as React from 'react'

type MagicLinkEmailProps = {
  /** First name or "there" if unknown. */
  firstName: string
  /** The full magic link URL generated by Supabase admin.generateLink. */
  magicLinkUrl: string
  /** "login" or "signup" — slightly different copy. */
  intent: 'login' | 'signup'
  /** User's email address — shown as reassurance that the link is for them. */
  email: string
}

export function MagicLinkEmail({ firstName, magicLinkUrl, intent, email }: MagicLinkEmailProps) {
  const isSignup = intent === 'signup'
  return (
    <Html>
      <Head />
      <Preview>
        {isSignup
          ? 'Confirm your Maestring account — click to get started'
          : 'Your Maestring sign-in link — valid for 20 minutes'}
      </Preview>
      <Body style={main}>
        <Container style={container}>
          {/* Brand mark */}
          <Text style={brand}>Maestring</Text>

          <Heading style={h1}>
            {isSignup ? `Welcome, ${firstName}! 🎉` : `Hi ${firstName} 👋`}
          </Heading>

          <Text style={text}>
            {isSignup
              ? "You're one click away from starting your AWS SAA-C03 prep. Click the button below to confirm your account and begin."
              : 'Click the button below to sign in to Maestring. No password needed.'}
          </Text>

          <Section style={btnSection}>
            <Button href={magicLinkUrl} style={button}>
              {isSignup ? 'Confirm account →' : 'Sign in to Maestring →'}
            </Button>
          </Section>

          <Section style={callout}>
            <Text style={calloutText}>
              🔒 This link is for <strong>{email}</strong> only. It expires in{' '}
              <strong>20 minutes</strong> and can only be used once.
            </Text>
          </Section>

          <Text style={mutedText}>
            If you didn&apos;t request this, you can safely ignore this email. Someone may have typed
            your address by mistake.
          </Text>

          <Hr style={hr} />
          <Text style={footer}>
            Maestring · AWS Certification Prep ·{' '}
            <a href="https://maestring.app" style={footerLink}>maestring.app</a>
          </Text>
        </Container>
      </Body>
    </Html>
  )
}

export default MagicLinkEmail

// ---------------------------------------------------------------------------
// Styles — dark theme matching the app
// ---------------------------------------------------------------------------
const main = { backgroundColor: '#0f1117', fontFamily: 'Inter, -apple-system, sans-serif' }
const container = { maxWidth: '560px', margin: '0 auto', padding: '40px 24px' }
const brand = { color: '#6366f1', fontSize: '20px', fontWeight: '700', marginBottom: '8px', letterSpacing: '-0.3px' }
const h1 = { color: '#ffffff', fontSize: '26px', fontWeight: '700', marginBottom: '16px', marginTop: '8px' }
const text = { color: '#a1a1aa', fontSize: '16px', lineHeight: '26px', marginBottom: '24px' }
const mutedText = { color: '#52525b', fontSize: '14px', lineHeight: '22px', marginTop: '24px' }
const btnSection = { textAlign: 'center' as const, margin: '32px 0' }
const button = {
  backgroundColor: '#6366f1',
  color: '#ffffff',
  borderRadius: '8px',
  padding: '14px 32px',
  fontSize: '16px',
  fontWeight: '600',
  textDecoration: 'none',
  display: 'inline-block',
}
const callout = {
  backgroundColor: '#1e1e2e',
  border: '1px solid #312e81',
  borderRadius: '8px',
  padding: '14px 18px',
  margin: '0',
}
const calloutText = { color: '#c7d2fe', fontSize: '14px', margin: 0, lineHeight: '22px' }
const hr = { borderColor: '#27272a', margin: '32px 0' }
const footer = { color: '#52525b', fontSize: '13px', textAlign: 'center' as const }
const footerLink = { color: '#6366f1', textDecoration: 'none' }
